name: Delete Dummy ORC File
on:
  push:
    branches:
      - fix-missing-orc

permissions:
  contents: read
  id-token: write

jobs:
  delete-orc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install "google-cloud-storage<3.0.0"

      - name: Delete Dummy ORC
        run: |
          python -c "
          from google.cloud import storage
          import sys
          import traceback
          
          try:
              print('Deleting dummy file from GCS...')
              client = storage.Client()
              bucket = client.bucket('tbd-2026l-321362-data')
              blob = bucket.blob('data/shakespeare/part-00000-dummy-c000.snappy.orc')
              if blob.exists():
                  blob.delete()
                  print('Dummy file deleted successfully!')
              else:
                  print('Dummy file already deleted or not found.')
          except Exception as e:
              print('Error:', e)
              traceback.print_exc()
              sys.exit(1)
          "
